Create database crime;
use  crime;
create table crimeRecord(
Id int NOT NULL Primary Key auto_increment,
year int NOT NULL,
region varchar(30) NOT NULL,
crimeType varchar(50) NOT NULL,
value int NOT NULL
);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Manitoba','Attempted murder',26);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Manitoba','Manslaughter',5);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Manitoba','Have stolen goods',707);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Manitoba','Frauds',2800);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Manitoba','Other crimes',44801);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Manitoba','Prostitution',108);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Manitoba','Gaming and betting',7);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Manitoba','Offensive weapons',1164);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Manitoba','Other Criminal Code',43522);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Manitoba','Federal Statutes',6344);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Saskatchewan','All offences, total',130617);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Saskatchewan','Criminal Code, total',124926);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Saskatchewan','Robbery',887);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Saskatchewan','Other violent crimes',15388);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Saskatchewan','Gaming and betting',5);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Saskatchewan','Offensive weapons',853);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Saskatchewan','Other Criminal Code',48315);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Saskatchewan','Federal Statutes',5691);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Alberta','All offences, total',278014);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Alberta','Criminal Code, total',268274);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Alberta','Crimes of violence',31462);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Alberta','Theft, motor vehicle',14847);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Alberta','Theft, over and under',79943);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Alberta','Have stolen goods',4436);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Alberta','Frauds',13223);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'British Columbia','Sexual assault with a weapon, bodily harm',102);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'British Columbia','Sexual assault, level 1',3785);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'British Columbia','Assault',40323);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'British Columbia','Assault, level 1',33946);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Yukon','Attempted murder',0);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Yukon','Frauds',176);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Yukon','Other crimes',2887);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Yukon','Prostitution',2);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Yukon','Gaming and betting',5);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Northwest Territories','Manslaughter',1);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Northwest Territories','Robbery',19);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Northwest Territories','Other violent crimes',2019);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Northwest Territories','Sexual assault',202);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Northwest Territories','Other Criminal Code',5516);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Northwest Territories','Federal Statutes',477);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Nunavut','All offences, total',5085);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Nunavut','Criminal Code, total',4887);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Nunavut','Other Criminal Code',2251);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (1999,'Nunavut','Federal Statutes',198);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Canada','All offences, total',2476520);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Canada','Criminal Code, total',2353926);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Newfoundland and Labrador','All offences, total',32393);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Newfoundland and Labrador','Federal Statutes',1621);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Prince Edward Island','All offences, total',9647);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Prince Edward Island','Criminal Code, total',9289);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Prince Edward Island','Murder',3);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Prince Edward Island','Attempted murder',1);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Prince Edward Island','Federal Statutes',358);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Nova Scotia','All offences, total',74149);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Nova Scotia','Criminal Code, total',71243);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Nova Scotia','Federal Statutes',2906);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'New Brunswick','All offences, total',53295);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'New Brunswick','Criminal Code, total',49320);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'New Brunswick','Other Criminal Code',20095);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'New Brunswick','Federal Statutes',3975);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Quebec','All offences, total',465908);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Quebec','Criminal Code, total',444342);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Quebec','Manslaughter',13);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Ontario','All offences, total',790041);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Ontario','Assault with weapon, bodily harm',13922);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Ontario','Federal Statutes',40808);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Manitoba','Other Criminal Code',45928);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Manitoba','Federal Statutes',6330);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Saskatchewan','All offences, total',135601);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Saskatchewan','Frauds',4155);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Alberta','All offences, total',274838);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Alberta','Criminal Code, total',264423);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Alberta','Theft, over and under',75663);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Alberta','Federal Statutes',10415);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'British Columbia','All offences, total',485641);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'British Columbia','Assault with weapon, bodily harm',6316);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Yukon','All offences, total',7521);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Yukon','Criminal Code, total',7218);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Yukon','Other Criminal Code',3617);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Yukon','Federal Statutes',303);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Northwest Territories','All offences, total',11942);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Northwest Territories','Criminal Code, total',11526);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Northwest Territories','Federal Statutes',416);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Nunavut','All offences, total',6130);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Nunavut','Criminal Code, total',5868);
INSERT INTO crimeRecord(year,region,crimeType,value) VALUES (2000,'Nunavut','Crimes of violence',1682);

select * from crimeRecord;